<?php

namespace SslCommerzPayment\Controller;

use App\Controller\AppController as BaseController;

class AppController extends BaseController
{
	public function initialize()
    {
        $this->loadComponent('Flash');
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}
